//! Linux UIX 应用 facade 的 capability descriptor 生成 Component。

use serde_json::{Value, json};

use crate::capabilities::{self, CapabilitySurface};

pub(crate) fn descriptor(capability: &'static str) -> Value {
    let definition = capabilities::definition_for_surface(CapabilitySurface::App, capability)
        .unwrap_or_else(|| unreachable!("UIX capability must be registered"));
    let mutation = definition.action.mutates();
    let constraints = match capability {
        capabilities::UI_ELEMENT_LOCATE_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "selectorSemantics": "exact-and",
            "selectorFields": ["automationId", "role", "name", "focused", "enabled", "action"],
            "coordinateSpace": "application-client",
            "coordinateUnit": "logical-px",
            "elementIdentity": "snapshot-revision",
            "hostCoordinateMappingPublished": false,
            "clickPointPublished": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_ELEMENT_WAIT_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "selectorSemantics": "exact-and",
            "selectorFields": ["automationId", "role", "name", "focused", "enabled", "action"],
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "stabilitySemantics": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_ELEMENT_ACTION_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-snapshot-element",
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_ELEMENT_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "sourceScope": "snapshot-scoped-element",
            "selectorSemantics": "exact-and",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "causalityConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "desktopInputInjected": false,
            "foregroundActivationRequested": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "noFallback": true,
        }),
        capabilities::UI_INPUT_KEY_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "supportedPhases": ["press"],
            "unavailableFeatures": ["down", "up", "hold", "repeat", "text"],
            "eventScope": "application-internal-ui-tree",
            "effectObservation": "not-exposed-by-uix-agent-v1",
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_KEY_SEQUENCE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "press_key",
            "maximumPresses": 64,
            "maximumPlannedDurationMs": 5000,
            "operationScope": "request-scoped-complete-press-sequence",
            "independentKeyOwnershipPublished": false,
            "textInputPublished": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_KEY_SEQUENCE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "press_key",
            "preflightScope": "all-keys-modifiers-and-semantic-wait-used-by-request",
            "maximumPresses": 64,
            "maximumPlannedDurationMs": 5000,
            "completeSequenceRequiredBeforePostcondition": true,
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "sameConnectionRevisionChain": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "requestScopedBalancedPresses": true,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "independentKeyOwnershipPublished": false,
            "textInputPublished": false,
            "keyHoldPublished": false,
            "keyRepeatPublished": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::UI_INPUT_KEY_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "press_key",
            "sourceScope": "single-complete-key-press",
            "pressSemantics": "complete-keydown-keyup",
            "selectorSemantics": "exact-and",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "causalityConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "independentKeyOwnershipPublished": false,
            "textInputPublished": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "noFallback": true,
        }),
        capabilities::UI_INPUT_SEQUENCE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredKeyWindowAction": "press_key",
            "requiredPointerWindowActionsAnyOf": ["pointer_move", "click_at"],
            "preflightScope": "all-actions-and-keys-used-by-request",
            "coordinateSpace": "client-logical-px",
            "stepKinds": ["press", "move", "click"],
            "requiresKeyAndPointer": true,
            "maximumSteps": 64,
            "maximumPlannedDurationMs": 5000,
            "sameConnectionRevisionChain": true,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_SEQUENCE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredKeyWindowAction": "press_key",
            "requiredPointerWindowActionsAnyOf": ["pointer_move", "click_at"],
            "preflightScope": "all-actions-keys-and-semantic-wait-used-by-request",
            "coordinateSpace": "client-logical-px",
            "stepKinds": ["press", "move", "click"],
            "requiresKeyAndPointer": true,
            "maximumSteps": 64,
            "maximumPlannedDurationMs": 5000,
            "completeSequenceRequiredBeforePostcondition": true,
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "sameConnectionRevisionChain": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "independentKeyOwnershipPublished": false,
            "independentButtonOwnershipPublished": false,
            "dragSupported": false,
            "doubleClickSemantics": false,
            "clickCountSemantics": false,
            "scrollSupported": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::UI_INPUT_POINTER_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "supportedActions": ["move", "click"],
            "unavailableFeatures": ["pointer-down", "pointer-up", "drag", "scroll", "double-click", "right-click", "middle-click"],
            "coordinateSpace": "client-logical-px",
            "eventScope": "application-internal-ui-tree",
            "effectObservation": "not-exposed-by-uix-agent-v1",
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_POINTER_CLICK_SEQUENCE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "click_at",
            "coordinateSpace": "client-logical-px",
            "button": "left",
            "maximumClicks": 64,
            "maximumPlannedDurationMs": 5000,
            "sameConnectionRevisionChain": true,
            "doubleClickSemantics": false,
            "clickCountSemantics": false,
            "independentButtonOwnershipPublished": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_POINTER_CLICK_SEQUENCE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "click_at",
            "preflightScope": "click-sequence-and-semantic-wait-used-by-request",
            "coordinateSpace": "client-logical-px",
            "clickSemantics": "ordinary-left-click-sequence",
            "maximumClicks": 64,
            "maximumPlannedDurationMs": 5000,
            "completeSequenceRequiredBeforePostcondition": true,
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "sameConnectionRevisionChain": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "requestScopedBalancedClicks": true,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "independentButtonOwnershipPublished": false,
            "dragSemantics": false,
            "doubleClickSemantics": false,
            "clickCountSemantics": false,
            "scrollSemantics": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::UI_INPUT_POINTER_CLICK_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "click_at",
            "coordinateSpace": "client-logical-px",
            "clickSemantics": "ordinary-left-click",
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "causalityConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "independentButtonOwnershipPublished": false,
            "doubleClickSemantics": false,
            "clickCountSemantics": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::UI_INPUT_POINTER_MOVE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "pointer_move",
            "coordinateSpace": "client-logical-px",
            "sourceScope": "single-application-internal-pointer-move",
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "clickSemantics": false,
            "independentButtonOwnershipPublished": false,
            "interpolationSemantics": false,
            "dragSemantics": false,
            "scrollSemantics": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::UI_INPUT_POINTER_MOVE_SEQUENCE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "pointer_move",
            "coordinateSpace": "client-logical-px",
            "minimumMoves": 2,
            "maximumMoves": 64,
            "maximumPlannedDurationMs": 5000,
            "sameConnectionRevisionChain": true,
            "interpolationSemantics": false,
            "desktopPointerMoved": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_POINTER_MOVE_SEQUENCE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "pointer_move",
            "preflightScope": "pointer-move-sequence-and-semantic-wait-used-by-request",
            "coordinateSpace": "client-logical-px",
            "moveSemantics": "ordered-hover-points",
            "minimumMoves": 2,
            "maximumMoves": 64,
            "maximumPlannedDurationMs": 5000,
            "completeSequenceRequiredBeforePostcondition": true,
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "sameConnectionRevisionChain": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "clickSupported": false,
            "keyPressSupported": false,
            "interpolationSupported": false,
            "dragSupported": false,
            "scrollSupported": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_POINTER_SEQUENCE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowActions": ["pointer_move", "click_at"],
            "coordinateSpace": "client-logical-px",
            "stepKinds": ["move", "click"],
            "requiresMoveAndClick": true,
            "maximumSteps": 64,
            "maximumPlannedDurationMs": 5000,
            "sameConnectionRevisionChain": true,
            "ordinaryLeftClicksOnly": true,
            "doubleClickSemantics": false,
            "independentButtonOwnershipPublished": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_POINTER_SEQUENCE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowActions": ["pointer_move", "click_at"],
            "coordinateSpace": "client-logical-px",
            "stepKinds": ["move", "click"],
            "requiresMoveAndClick": true,
            "maximumSteps": 64,
            "maximumPlannedDurationMs": 5000,
            "completeSequenceRequiredBeforePostcondition": true,
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "sameConnectionRevisionChain": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "ordinaryLeftClicksOnly": true,
            "requestScopedBalancedClicks": true,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "independentButtonOwnershipPublished": false,
            "dragSupported": false,
            "doubleClickSemantics": false,
            "clickCountSemantics": false,
            "scrollSupported": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::UI_INPUT_POINTER_DRAG => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowActions": ["pointer_down", "pointer_move", "pointer_up"],
            "coordinateSpace": "client-logical-px",
            "button": "left",
            "requestScopedBalancedButtons": true,
            "bestEffortReleaseAfterDownFailure": true,
            "independentButtonOwnershipPublished": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::UI_INPUT_POINTER_DRAG_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowActions": ["pointer_down", "pointer_move", "pointer_up"],
            "coordinateSpace": "client-logical-px",
            "button": "left",
            "requestScopedBalancedButtons": true,
            "bestEffortReleaseAfterDownFailure": true,
            "postconditionRequiresConfirmedRelease": true,
            "postconditionSemantics": "exact-and-unique-or-missing",
            "conditionKinds": ["unique", "missing"],
            "sameAuthenticatedConnectionUsed": true,
            "semanticRevisionWaitUsed": true,
            "providerPolling": false,
            "waitProtocolUsed": true,
            "causalityConfirmed": false,
            "applicationConsumptionConfirmed": false,
            "finalUIStateConfirmed": false,
            "finalStateReached": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "desktopPointerMoved": false,
            "independentButtonOwnershipPublished": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
            "noFallback": true,
        }),
        capabilities::WINDOW_LIFECYCLE_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "supportedActions": ["restore", "minimize", "maximize", "resize"],
            "unavailableActions": ["move"],
            "resizeCoordinateSpace": "client-logical-px",
            "effectObservation": "not-exposed-by-uix-agent-v1",
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_LIFECYCLE_SEQUENCE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "supportedActions": ["restore", "minimize", "maximize", "resize"],
            "requiredDistinctActionKinds": 2,
            "maximumActions": 16,
            "maximumPlannedDurationMs": 5000,
            "sameConnectionRevisionChain": true,
            "resizeCoordinateSpace": "client-logical-px",
            "arbitraryWindowMoveSupported": false,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "compositorFinalStateConfirmed": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_LIFECYCLE_SEQUENCE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "supportedActions": ["restore", "minimize", "maximize", "resize"],
            "conditionKinds": ["visibility", "focus", "client-size", "window-flags"],
            "requiredDistinctActionKinds": 2,
            "minimumActions": 2,
            "maximumActions": 16,
            "maximumPlannedDurationMs": 5000,
            "completeSequenceRequiredBeforeCondition": true,
            "sameAuthenticatedConnectionUsed": true,
            "sameConnectionRevisionChain": true,
            "providerPolling": true,
            "waitProtocolUsed": false,
            "frameworkConditionMatchedAfterCompleteSequence": true,
            "transactionSemantics": false,
            "rollbackSemantics": false,
            "causalityConfirmed": false,
            "compositorFinalStateConfirmed": false,
            "arbitraryWindowMoveSupported": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
        }),
        capabilities::WINDOW_LIFECYCLE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "supportedActions": ["restore", "minimize", "maximize", "resize"],
            "conditionKinds": ["visibility", "focus", "client-size", "window-flags"],
            "sameAuthenticatedConnectionUsed": true,
            "providerPolling": true,
            "waitProtocolUsed": false,
            "frameworkConditionMatchedAfterDispatch": true,
            "compositorFinalStateConfirmed": false,
            "arbitraryWindowMoveSupported": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_CLOSE_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "effectObservation": "separate-window.closed.wait@2",
            "finalStateClaimed": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_CLOSE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "close_window",
            "sameAuthenticatedConnectionUsed": true,
            "waitProtocolUsed": true,
            "providerPolling": false,
            "terminalReplyRequired": true,
            "connectionCloseAcceptedAsProof": false,
            "causalityConfirmed": false,
            "applicationClosedConfirmed": false,
            "foregroundActivationRequested": false,
            "desktopInputInjected": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "fallback": "none",
        }),
        capabilities::WINDOW_STATE_READ => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredNegotiation": "hello.capabilities.window_state_fields",
            "observationSource": "uix-framework-current",
            "coordinateSpace": "client-logical-px",
            "compositorFinalStateConfirmed": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_STATE_WAIT => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredNegotiation": ["logical_width", "logical_height", "maximized", "minimized", "fullscreen", "focused"],
            "conditionKinds": ["visibility", "focus", "client-size", "window-flags"],
            "observationSource": "uix-framework-current",
            "coordinateSpace": "client-logical-px",
            "sameAuthenticatedConnectionUsed": true,
            "providerPolling": "list_windows",
            "waitProtocolUsed": false,
            "compositorFinalStateConfirmed": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_SCREENSHOT_V2 => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredNegotiation": ["screenshot", "max_screenshot_bytes", "max_response_bytes"],
            "sourceScope": "uix-application-surface",
            "generationRevalidatedAfterCapture": true,
            "atomicPngOutput": true,
            "globalWindowCaptureClaimed": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_ACTIVATE => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "activate_window",
            "requestAcceptedDoesNotGuaranteeFocus": true,
            "sameConnectionFocusObservation": true,
            "foregroundConsentRequired": true,
            "globalWindowActivationClaimed": false,
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
        capabilities::WINDOW_ACTIVATE_TRANSITION => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "requiredWindowAction": "activate_window",
            "requiredNegotiation": ["focused"],
            "sameAuthenticatedConnectionUsed": true,
            "providerPolling": true,
            "waitProtocolUsed": false,
            "requestAcceptedDoesNotGuaranteePersistentFocus": true,
            "causalityConfirmed": false,
            "finalFocusStateGuaranteed": false,
            "foregroundConsentRequired": true,
            "foregroundActivationRequested": true,
            "desktopInputInjected": false,
            "nativeIdentityExposed": false,
            "transportIdentityExposed": false,
            "x11Used": false,
            "noFallback": true,
        }),
        _ => json!({
            "provider": "uix-agent-v1",
            "coverage": "opt-in-uix-agent-applications",
            "target": "exact-window-generation",
            "noFallback": true,
            "nativeIdentityExposed": false,
        }),
    };
    json!({
        "id": definition.id,
        "version": if matches!(
            capability,
            capabilities::WINDOW_REVISION_WAIT
                | capabilities::WINDOW_STATE_READ
                | capabilities::WINDOW_STATE_WAIT
                | capabilities::WINDOW_ACTIVATE
                | capabilities::WINDOW_ACTIVATE_TRANSITION
                | capabilities::UI_INPUT_POINTER_DRAG
                | capabilities::UI_INPUT_POINTER_DRAG_TRANSITION
                | capabilities::UI_INPUT_KEY_SEQUENCE
                | capabilities::UI_INPUT_KEY_SEQUENCE_TRANSITION
                | capabilities::UI_INPUT_SEQUENCE
                | capabilities::UI_INPUT_SEQUENCE_TRANSITION
                | capabilities::UI_INPUT_POINTER_CLICK_SEQUENCE
                | capabilities::UI_INPUT_POINTER_CLICK_SEQUENCE_TRANSITION
                | capabilities::UI_INPUT_POINTER_MOVE_SEQUENCE
                | capabilities::UI_INPUT_POINTER_MOVE_SEQUENCE_TRANSITION
                | capabilities::UI_INPUT_POINTER_SEQUENCE
                | capabilities::UI_INPUT_POINTER_SEQUENCE_TRANSITION
                | capabilities::UI_INPUT_POINTER_CLICK_TRANSITION
                | capabilities::UI_INPUT_POINTER_MOVE_TRANSITION
                | capabilities::WINDOW_LIFECYCLE_SEQUENCE
                | capabilities::WINDOW_LIFECYCLE_SEQUENCE_TRANSITION
                | capabilities::WINDOW_LIFECYCLE_TRANSITION
                | capabilities::UI_ELEMENT_TRANSITION
                | capabilities::WINDOW_CLOSE_TRANSITION
                | capabilities::UI_INPUT_KEY_TRANSITION
        ) { 1 } else { 2 },
        "verb": definition.action.as_str(),
        "availability": "available",
        "execution": definition.execution,
        "executionRealm": definition.execution_realm,
        "requiresConfirmation": mutation,
        "requiresForegroundConsent": definition.requires_foreground_consent,
        "inputSchema": definition.input_schema,
        "constraints": constraints,
    })
}
